# Generated by Django 3.1.7 on 2021-08-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_categories_description'),
        ('Accounts', '0002_auto_20210825_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='Shop.Product'),
        ),
    ]
