# Generated by Django 3.1.7 on 2021-08-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_categories_description'),
        ('Accounts', '0003_auto_20210825_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.IntegerField(default=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='Shop.Product'),
        ),
    ]
