# Generated by Django 3.1.7 on 2021-04-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20210417_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_image',
            field=models.ImageField(blank=True, upload_to='uploaded_images/'),
        ),
    ]
