# Generated by Django 3.1.7 on 2021-08-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
