# Generated by Django 3.1.7 on 2021-08-08 21:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20210806_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_icons',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_info',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
